idf_component_register(SRCS "main.c" "gpio/spi.c" "radio/sx1262.c" "parse/nmea.c" "gps/neo6m.c" "sensors/bme280_port.c" "sensors/adxl345_port.c" "sensors/itg3205.c" "lib/BME280_SensorAPI/bme280.c" "lib/adxl345/src/driver_adxl345.c" "gpio/i2c.c" "tasks/collection.c" "tasks/transmission.c" "tasks/gps_collection.c"
                    INCLUDE_DIRS "." "gpio" "radio" "tasks" "parse" "gps" "sensors" "lib/BME280_SensorAPI" "lib/adxl345/src")